name: Apps FpML Publish Packages 1.0-SNAPSHOT

on:
  milestone:
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        settings-path: ${{ github.workspace }}

    - name: List the Settings Directory
      run: |
        ls -la $GITHUB_WORKSPACE/.github/workflows/settings.xml

    - name: Cat the Provided Settings
      run: |
        cat $GITHUB_WORKSPACE/.github/workflows/settings.xml

    - name: Cat the Generated Settings
      run: |
        cat $GITHUB_WORKSPACE/settings.xml

    - name: Deploy Maven Artifacts
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -X -B deploy -DskipTests=true --file pom.xml 
      env:
        USERNAME_PACKAGE_READ_WRITE_DELETE: jjsteenkamp
        TOKEN_PACKAGE_READ_WRITE_DELETE: ${{ secrets.token_package_read_write_delete }}







