name: Apps FpML Publish Packages 1.0-SNAPSHOT

on:
  milestone:
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        settings-path: ${{ github.workspace }}

    - name: Cache Maven Modules
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-platform-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-platform-

    - name: Cache Third-Party
      uses: actions/cache@v1
      with:
        path: third-party
        key: ${{ runner.os }}-maven-platform-third-party-${{ hashFiles('third-party/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-platform-third-party-

    - name: List the Settings Directory
      run: |
        ls -la $GITHUB_WORKSPACE/.github/workflows/settings.xml

    - name: Cat the Provided Settings
      run: |
        cat $GITHUB_WORKSPACE/.github/workflows/settings.xml

    - name: Cat the Generated Settings
      run: |
        cat $GITHUB_WORKSPACE/settings.xml

    - name: Deploy Maven Artifacts
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B deploy --file pom.xml -DskipTests=true
      env:
        USERNAME_PACKAGE_READ_WRITE_DELETE: jjsteenkamp
        TOKEN_PACKAGE_READ_WRITE_DELETE: ${{ secrets.token_package_read_write_delete }}







